"use client";
import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiFetch } from "@/lib/auth";
interface Work {user_id:string;email:string;submitted:number;total:number;on_time:number;assignment_total:number;done_readings:number;grade_distribution:Record<string,number>}
interface Learning {user_id:string;self_reading_count:number;speaking_count:number;speaking_avg_score:number|null;speaking_last_7_days:number;writing_count:number;writing_avg_score:number|null;mistake_count:number;mistake_mastering:number}
export default function StudentDetail(){const{id,userId}=useParams<{id:string;userId:string}>();const[work,setWork]=useState<Work|null>(null);const[learning,setLearning]=useState<Learning|null>(null);const[error,setError]=useState("");useEffect(()=>{Promise.all([apiFetch(`/api/classrooms/${id}/assignments/stats`),apiFetch(`/api/classrooms/${id}/assignments/student-profiles`)]).then(async([a,b])=>{const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error);if(!b.ok)throw new Error(y.error);setWork((x.all_students??[]).find((v:Work)=>v.user_id===userId)??null);setLearning((y.profiles??[]).find((v:Learning)=>v.user_id===userId)??null)}).catch(e=>setError(e instanceof Error?e.message:"加载失败"))},[id,userId]);return <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6"><Link href={`/teaching/${id}/members/profiles`} className="text-sm text-zinc-500 hover:text-orange-600">← 返回学生档案</Link><h1 className="mt-3 text-3xl font-bold">{work?.email??"学生详情"}</h1>{error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{!work&&!error?<p className="mt-8 text-zinc-400">加载中…</p>:work&&<div className="mt-8 space-y-8"><Section title="作业评分统计"><Cards items={[["已提交",`${work.submitted}/${work.total}`],["按时提交",`${work.on_time}/${work.assignment_total}`],["已批改",String(Object.values(work.grade_distribution).reduce((a,b)=>a+b,0))],["等级分布",Object.entries(work.grade_distribution).map(([g,c])=>`${g}×${c}`).join(" ")||"—"]]}/></Section><Section title="平时作业情况"><p className="rounded-xl border bg-white p-5 text-sm text-zinc-600">预习与课后作业合计完成 <b className="text-orange-600">{work.submitted}</b>/{work.total}；预习完成 {work.done_readings}，笔头作业按时提交 {work.on_time}。</p></Section><Section title="课外学习情况"><Cards items={[["自主阅读",`${learning?.self_reading_count??0} 篇`],["口语练习",`${learning?.speaking_count??0} 次`],["写作润色",`${learning?.writing_count??0} 次`],["错题/掌握中",`${learning?.mistake_count??0}/${learning?.mistake_mastering??0}`]]}/><p className="mt-3 text-xs text-zinc-500">近 7 天口语 {learning?.speaking_last_7_days??0} 次 · 口语平均 {learning?.speaking_avg_score??"—"} · 写作平均 {learning?.writing_avg_score??"—"}</p></Section></div>}</div>}
function Section({title,children}:{title:string;children:ReactNode}){return <section><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3">{children}</div></section>}
function Cards({items}:{items:string[][]}){return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{items.map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4 text-center"><p className="text-xl font-bold text-orange-600">{value}</p><p className="mt-1 text-xs text-zinc-500">{label}</p></div>)}</div>}
