"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiFetch } from "@/lib/auth";

interface WorkStat { user_id:string; email:string; submitted:number; total:number; on_time:number; assignment_total:number; submission_rate:number; on_time_rate:number; grade_average:number; grade_distribution:Record<string,number>; }
interface Analysis { summary:string; weaknesses:string[]; frequentErrors:string[]; commonQuestions:string[]; generatedAt:string; }

export default function StudentProfilesPage() {
  const { id }=useParams<{id:string}>(); const [students,setStudents]=useState<WorkStat[]>([]); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [counts,setCounts]=useState<{readings:number;assignments:number;mistakes:number}|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{Promise.all([apiFetch(`/api/classrooms/${id}/assignments/stats`),apiFetch(`/api/classrooms/${id}/learning-analysis`)]).then(async([a,b])=>{const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error);if(!b.ok)throw new Error(y.error);setStudents(x.ranking??x.all_students??[]);setCounts(y.evidence_counts??null)}).catch(e=>setError(e instanceof Error?e.message:"加载失败"))},[id]);
  async function generate(){setBusy(true);setError("");try{const r=await apiFetch(`/api/classrooms/${id}/learning-analysis`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error);setAnalysis(d.analysis)}catch(e){setError(e instanceof Error?e.message:"分析失败")}finally{setBusy(false)}}
  return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><Link href={`/teaching/${id}/members`} className="text-sm text-zinc-500 hover:text-orange-600">← 返回班级成员</Link><h1 className="mt-3 text-3xl font-bold">学生档案</h1><p className="mt-2 text-zinc-600">点击学生查看个人档案，并根据动态证据生成全班学情分析。</p>{error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
  <section className="mt-8"><h2 className="text-lg font-semibold">全班学生</h2><div className="mt-3 space-y-2">{students.length===0?<p className="rounded-xl border border-dashed p-8 text-center text-zinc-400">暂无学生数据</p>:students.map(s=><Link key={s.user_id} href={`/teaching/${id}/members/profiles/${s.user_id}`} className="flex items-center justify-between rounded-xl border bg-white p-4 hover:border-orange-200"><div><p className="font-medium">{s.email}</p><p className="mt-1 text-xs text-zinc-500">已交 {s.submitted}/{s.total} · 按时 {s.on_time}/{s.assignment_total} · {Object.entries(s.grade_distribution).map(([g,c])=>`${g}×${c}`).join(" ")||"未评分"}</p></div><span className="text-sm text-orange-600">查看档案 →</span></Link>)}</div></section>
  <section className="mt-8"><h2 className="text-lg font-semibold">全班作业完成情况排名</h2><p className="text-xs text-zinc-400">完成度 35%、按时率 25%、教师评分质量 40%。</p><div className="mt-3 overflow-x-auto rounded-xl border bg-white"><table className="min-w-full text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="p-3 text-left">排名</th><th className="p-3 text-left">学生</th><th className="p-3">完成率</th><th className="p-3">按时率</th><th className="p-3">评分质量</th></tr></thead><tbody>{students.map((s,i)=><tr key={s.user_id} className="border-t"><td className="p-3">{i+1}</td><td className="p-3 font-medium">{s.email}</td><td className="p-3 text-center">{Math.round(s.submission_rate*100)}%</td><td className="p-3 text-center">{Math.round(s.on_time_rate*100)}%</td><td className="p-3 text-center">{s.grade_average?s.grade_average.toFixed(1):"—"}</td></tr>)}</tbody></table></div></section>
  <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">全班整体学情分析</h2><p className="text-xs text-zinc-400">证据：预习 {counts?.readings??0} 条、作业 {counts?.assignments??0} 条、错题 {counts?.mistakes??0} 条。</p></div><button onClick={generate} disabled={busy} className="rounded-lg bg-orange-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?"正在分析…":analysis?"重新生成":"生成学情分析"}</button></div>{analysis?<div className="mt-3 rounded-xl border bg-white p-5"><p className="whitespace-pre-wrap text-sm leading-7">{analysis.summary}</p><div className="mt-4 grid gap-4 md:grid-cols-3"><List title="共性薄弱点" items={analysis.weaknesses}/><List title="高频错误" items={analysis.frequentErrors}/><List title="常见疑问" items={analysis.commonQuestions}/></div><p className="mt-4 text-xs text-zinc-400">生成时间：{new Date(analysis.generatedAt).toLocaleString("zh-CN")}</p></div>:<div className="mt-3 rounded-xl border border-dashed p-8 text-center text-zinc-400">点击生成，实时汇总当前学生问题、教师反馈和错题模式。</div>}</section></div>
}
function List({title,items}:{title:string;items:string[]}){return <div><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-sm text-zinc-600">{items.length?items.map((x,i)=><li key={i}>• {x}</li>):<li>暂无足够数据</li>}</ul></div>}
