"use client";
import { useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { apiFetch } from "@/lib/auth";
interface Item { question_index:number; student_answer:string; reference_answer:string; is_correct:boolean; issues:string; suggested_grade:string }
interface Result { student_id:string; submission_id?:string; items:Item[]; grade:string; feedback:string; saved?:boolean }
const GRADES=["A+","A","B+","B","C+","C","D"];
export default function BatchReviewPage(){const p=useParams<{id:string;assignmentId:string}>();const[files,setFiles]=useState<File[]>([]);const[results,setResults]=useState<Result[]>([]);const[busy,setBusy]=useState("");const[error,setError]=useState("");
async function run(){if(!files.length)return setError("请先上传参考答案图片");setBusy("正在 OCR 与 AI 对照…");setError("");try{const form=new FormData();files.forEach(f=>form.append("teacher_answer_files",f));const r=await apiFetch(`/api/classrooms/${p.id}/assignments/${p.assignmentId}/batch-review`,{method:"POST",body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||"批改失败");const ids=new Map<string,string>((d.submissions??[]).map((x:{user_id:string;id:string})=>[x.user_id,x.id]));setResults((d.results??[]).map((x:Result)=>({...x,submission_id:ids.get(x.student_id),grade:x.items?.[0]?.suggested_grade||"B",feedback:(x.items??[]).map((i:Item)=>`第${i.question_index}题：${i.is_correct?"正确":"需修改"}${i.issues?`；${i.issues}`:""}`).join("\n")})))}catch(e){setError(e instanceof Error?e.message:"批改失败")}finally{setBusy("")}}
async function adopt(n:number){const x=results[n];if(!x.submission_id)return;setBusy(`s${n}`);try{const r=await apiFetch(`/api/classrooms/${p.id}/assignments/${p.assignmentId}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submission_id:x.submission_id,grade:x.grade,feedback:x.feedback})});const d=await r.json();if(!r.ok)throw new Error(d.error||"保存失败");setResults(v=>v.map((a,i)=>i===n?{...a,saved:true}:a))}catch(e){setError(e instanceof Error?e.message:"保存失败")}finally{setBusy("")}}
return <div className="mx-auto max-w-5xl px-4 py-10"><Link href={`/teaching/${p.id}/assignments/${p.assignmentId}`} className="text-sm text-zinc-500">← 返回作业详情</Link><h1 className="mt-4 text-2xl font-bold">一键批改</h1><p className="mt-2 text-sm text-zinc-500">AI 结果仅作建议，教师确认“采纳”后才写入成绩。</p><section className="mt-6 rounded-2xl border bg-white p-6"><input type="file" multiple accept="image/*,.pdf,.docx" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,5))}/><p className="mt-2 text-xs text-zinc-400">当前 OCR 稳定支持图片；PDF/DOCX 请先转成图片。</p><button onClick={run} disabled={!!busy||!files.length} className="mt-4 rounded-lg bg-orange-600 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy&&!busy.startsWith("s")?busy:"开始一键批改"}</button></section>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-4">{results.map((x,n)=><section key={x.student_id} className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">学生 {x.student_id}</h2>{x.items.map(i=><div key={i.question_index} className="mt-3 rounded-xl bg-zinc-50 p-3 text-sm"><b className={i.is_correct?"text-emerald-700":"text-red-700"}>第 {i.question_index} 题 · {i.is_correct?"正确":"需修改"}</b><p>学生：{i.student_answer||"（空）"}</p><p>参考：{i.reference_answer}</p>{i.issues&&<p className="text-red-700">问题：{i.issues}</p>}</div>)}<div className="mt-4 grid gap-3 sm:grid-cols-[10rem_1fr]"><select value={x.grade} onChange={e=>setResults(v=>v.map((a,i)=>i===n?{...a,grade:e.target.value,saved:false}:a))} className="rounded-lg border p-2">{GRADES.map(g=><option key={g}>{g}</option>)}</select><textarea value={x.feedback} onChange={e=>setResults(v=>v.map((a,i)=>i===n?{...a,feedback:e.target.value,saved:false}:a))} rows={4} className="rounded-lg border p-3 text-sm"/></div><button onClick={()=>adopt(n)} disabled={busy===`s${n}`||x.saved} className="mt-3 rounded-lg bg-orange-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{x.saved?"已采纳":busy===`s${n}`?"保存中…":"采纳"}</button></section>)}</div></div>}
